name = "BifurcationExplorer"
uuid = "e3384b18-ca85-4098-820c-8e64a868b473"
authors = ["Grisha Szep"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
